export const siteConfig = {
  name: "WP Design",
  tagline: "Twój przewodnik po kasynach online w Polsce",
  url: "https://wp-design.org",
  description: "WP Design to niezależny portal o kasynach online dla polskich graczy. Recenzje, bonusy, sloty, płatności BLIK i poradniki – wszystko o legalnym hazardzie online.",
  language: "pl",
  moneyPageUrl: "https://vulkankasyno.pl",
  moneyPageAnchor: "Vulkan Vegas",
  moneyPageAnchorAlt: "najlepsze kasyno online",
  moneyPageBonus: "bonus powitalny do 4000 PLN",
  featuredPostSlug: "vulkan-vegas-recenzja",
  author: "Redakcja WP Design",
  wpVersion: "6.5.2",
  wpTheme: "wpdesign-theme",
}
